### ISSUE TITLE
assembler.jar is an invalid jarfile

### ISSUE THREAD

**Issue by Kleadron** [2xsaiko/retrocomputers#3]
Any attempt to run it or open it in 7-zip (which usually works for all jar files) fails.

**Comment by dblsaiko** [comment]
assembler.jar is a symlink (probably to a nonexisting file, unless you also cloned [https://github.com/2xsaiko/XC8010-Assembler][1] in the directory you cloned this repo in). You can just replace the symlink with the actual file from the other repo and it will work. It's a pretty jank setup that I want to improve at some point.

EDIT: Oh wait, that repo is private/archived. You can get the file [here][2] instead.

[1]: https://github.com/2xsaiko/XC8010-Assembler
[2]: https://files.dblsaiko.net/s/8oWLPJi9aQx5XYY

**Comment by Kleadron** [comment]
Ah, alright. I'll try messing with that.
Out of curiosity, what are the exact differences between the XC8010 and the 65el02? I wonder how hard it is to compile assembly from redpower 2 to retrocomputers

**Comment by dblsaiko** [comment]
It has the same instruction set, although I haven't implemented all the instructions yet. I guess there's some differences in implementation though, since I tested the original RP2 disks with this and they don't boot correctly.

**Comment by Kleadron** [comment]
Using the 64tass compiler from BiGFooT's basic port, the computer fails to boot a simple program that uses an MCFS format disk, even though retrocomputers seems to use the same boot code.
Loading the Extended FORTH disk in the redpower 2 emulator causes a lot of bad stuff to happen, so it looks like it's a little more than just unimplemented instructions.
I tried using your compiler, but it seems to use a different kind of assembly format and I don't know what the options for it are.

**Comment by dblsaiko** [comment]
What do you mean, it seems to use the same boot code? I wrote the bootloader myself, it uses roughly the same way of loading code but no guarantee it's actually compatible, especially with MCFS disks (didn't those need a special bootloader even with original RP2?)

As for my assembler, yeah, it's my own jank format that I made not knowing a lot about existing assembly conventions. It shouldn't make a difference when assembling programs though, since the instruction set and the way instructions are decoded are (or should be) the same.

As for the differences in implementation of the instruction set, I do know one: BiGFooT's emulator had a "stack bug" or some such option that allowed fixing a bug in the original RP2 emulator, I believe relating to the stack pointer offset being one off a normal 6502. My emulator doesn't have that bug in the first place, so you might try turning that off in BiGFooT's emulator and see if you get any further loading the image.

**Comment by Kleadron** [comment]
I had thought that it used the same enhanced boot code by BiGFooT since it has the exact same status messages, or at least they're really similar.
MCFS disks can be loaded in stock RP2 without a special bootloader though. Enabling the stack bug fix does not allow it to load further. Something weird is going on with it. 
Is it possible the memory structure is different? http://www.eloraam.com/blog/2012/04/22/rp-control-internals/

**Comment by dblsaiko** [comment]
Nope, the memory structure is the same, I was actually working off that documentation when I initially implemented this. I think the only way to really figure out what's going on is to look at the bootloader assembly or the Forth assembly and use the debugger in the standalone emulator to compare what it executes against the assembly, where it starts deviating
